// Generated by tools/codegen/analysis-types.ts from
// nnj-grammar/schema/analysis-document.schema.json. Do not edit by hand;
// change the Rust structs, then run `npm run gen:types`.

import { z } from "zod";

const index = z.int().nonnegative();

export const DictionaryGloss = z.object({
  entry_seq: z.int(),
  gloss: z.string(),
  pos: z.array(z.string()),
});

export type DictionaryGloss = z.infer<typeof DictionaryGloss>;

export const AnalyzedToken = z.object({
  id: z.string(),
  surface: z.string(),
  pos1: z.string(),
  pos2: z.string(),
  pos3: z.string(),
  pos4: z.string(),
  conj_type: z.string(),
  conj_form: z.string(),
  base_form: z.string(),
  reading: z.string(),
  byte_start: index,
  byte_end: index,
  position: index,
  glosses: z.array(DictionaryGloss),
});

export type AnalyzedToken = z.infer<typeof AnalyzedToken>;

/** One named token range captured while matching a rule. */
export const PatternCapture = z.object({
  name: z.string(),
  token_start: index,
  token_end: index,
});

export type PatternCapture = z.infer<typeof PatternCapture>;

export const MatchScore = z.object({
  fallback: z.boolean(),
  priority: z.int(),
  span_length: index,
  core_specificity: index,
  context_specificity: index,
  wildcard_steps: index,
  optional_steps: index,
});

export type MatchScore = z.infer<typeof MatchScore>;

/** Catalog metadata assigned by the loader rather than grammar TOML. */
export const CatalogSource = z.object({
  id: z.string(),
  label: z.string(),
});

export type CatalogSource = z.infer<typeof CatalogSource>;

export const MatchProvenance = z.object({
  source: CatalogSource,
  rule_id: z.string(),
  variant_id: z.string(),
});

export type MatchProvenance = z.infer<typeof MatchProvenance>;

export const DisplayMatch = z.object({
  id: z.string(),
  rule_name: z.string(),
  jlpt: z.string(),
  meaning_en: z.string(),
  hint: z.string().nullable(),
  sense_id: z.string().nullable(),
  ambiguity_group: z.string().nullable(),
  captures: z.array(PatternCapture),
  token_start: index,
  token_end: index,
  score: MatchScore,
  provenance: z.array(MatchProvenance),
});

export type DisplayMatch = z.infer<typeof DisplayMatch>;

export const SecondaryReason = z.enum([
  "contained_by_stronger_match",
  "overlaps_stronger_match",
]);

export type SecondaryReason = z.infer<typeof SecondaryReason>;

export const SecondaryMatch = z.object({
  id: z.string(),
  matched: DisplayMatch,
  reason: SecondaryReason,
  blocked_by: z.string().nullable(),
});

export type SecondaryMatch = z.infer<typeof SecondaryMatch>;

/**
 * - `document`: 文章 — the whole pasted input; always the root.
 * - `sentence`: 文 — one sentence, split at 句点 runs by the chunker.
 * - `bunsetsu`: 文節 — one content word plus its trailing function words.
 * - `word`: 単語 — one dictionary word spanning several short-unit tokens
 *   (自動+販売+機 → 自動販売機); always a leaf.
 * - `token`: One UniDic short-unit token; always a leaf.
 */
export const TreeNodeKind = z.enum([
  "document",
  "sentence",
  "bunsetsu",
  "word",
  "token",
]);

export type TreeNodeKind = z.infer<typeof TreeNodeKind>;

export const AnalysisTreeNode = z.object({
  id: z.string(),
  kind: TreeNodeKind,
  token_start: index.nullable(),
  token_end: index.nullable(),
  token_id: z.string().nullable(),
  /** Primary grammar matches whose span this node is the smallest cover of. */
  match_ids: z.array(z.string()),
  secondary_match_ids: z.array(z.string()),
});

export type AnalysisTreeNode = z.infer<typeof AnalysisTreeNode>;

export const AnalysisTreeEdge = z.object({
  parent_id: z.string(),
  child_id: z.string(),
  order: index,
});

export type AnalysisTreeEdge = z.infer<typeof AnalysisTreeEdge>;

export const AnalysisTree = z.object({
  root_id: z.string(),
  nodes: z.array(AnalysisTreeNode),
  edges: z.array(AnalysisTreeEdge),
});

export type AnalysisTree = z.infer<typeof AnalysisTree>;

export const AnalysisDocument = z.object({
  schema_version: z.literal(3),
  input: z.string(),
  tokens: z.array(AnalyzedToken),
  primary_matches: z.array(DisplayMatch),
  secondary_matches: z.array(SecondaryMatch),
  tree: AnalysisTree,
});

export type AnalysisDocument = z.infer<typeof AnalysisDocument>;
